version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
    - APP_ENV=DOCKER

    links:
    - db

  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
      - ./db_schema:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=flaskit
